name: firebase_crashlytics
description:
  Flutter plugin for Firebase Crashlytics. It reports uncaught errors to the
  Firebase console.
version: 3.1.2
homepage: https://firebase.google.com/docs/crashlytics
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_crashlytics/firebase_crashlytics

false_secrets:
  - example/**

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core: ^2.10.0
  firebase_core_platform_interface: ^4.6.0
  firebase_crashlytics_platform_interface: ^3.4.1
  flutter:
    sdk: flutter
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.crashlytics
        pluginClass: FlutterFirebaseCrashlyticsPlugin
      ios:
        pluginClass: FLTFirebaseCrashlyticsPlugin
